# AI Camera Node Parameters for PiCarX
# Indent: 2 spaces
# ROS 2 YAML parameter file

picarx_rpiai_camera_node:
  ros__parameters:
    detection_threshold: 0.60
    frame_id: "camera_link"
    ignore_dash_labels: false
    inference_rate: 15
    iou_threshold: 0.70
    labels_file: "/home/gzub/ros2-picarx/raspberrypi_ai_camera_ros2/labels/coco_yolo.txt"
    max_detections: 10
    network_package: "/home/gzub/ros2-picarx/raspberrypi_ai_camera_ros2/networks/imx500_network_yolov8n_640x640_pp.rpk"
    output_directory: "image_out/"
    preserve_aspect_ratio: false
    save_images: false
